bt: new no_opt inline functional memories bt_memories tensor

bt_memories:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDC/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDC8/$(OPT) a100=1 ptxas=1	
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDC16/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDC64/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG64/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG64_STRONG_DRAM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG8/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG16/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG128/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDS_U8/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDS_U16/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDS_U64/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDS_U128/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/ST_E_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG8/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG8_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG16/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG64/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG128/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STS/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STS8/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STS16/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STS64/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STS128/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG8_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG8_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG16_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG16_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG128_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG128_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG16_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG64_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG128_STRONG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG8_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG16_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG64_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG128_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG8_STRONG_DRAM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG16_STRONG_DRAM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG_STRONG_DRAM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG128_STRONG_DRAM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG8_CONSTANT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG16_CONSTANT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG_CONSTANT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG64_CONSTANT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG128_CONSTANT/$(OPT) a100=1



inline:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/NOP/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/BAR/$(OPT) a100=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/IMAD_IADD/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/IMAD_IADD_v2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/LOP3_LUT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/SHFL_IDX/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/IDP_4A/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/PRMT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/NANOSLEEP/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/LEA/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/ST_E_STRONG_L1/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/STG64_L1_HIT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/STG_L2_HIT/$(OPT) a100=1


no_opt:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/MOV/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/F2F_64_32_DADD/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/F2F_32_64_FADD/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/PLOP3_LUT/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/BRA/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/ISETP_GE_AND/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/ISETP_NE_AND/$(OPT) a100=1 ptxas=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/TLDADD/$(OPT) a100=1 ptxas=1

investigate:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/F2F_64_32_STG/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/F2F_32_64_STG/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/F2F_16_32_ADD/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/F2F_32_16_ADD/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/LDC_STG/$(OPT) a100=1 ptxas=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/LDS/$(OPT) a100=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/TLD/$(OPT) a100=1 ptxas=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/TLDSTG/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/LDG/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/P2R/$(OPT) a100=1 ptxas=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/F2F_32_64_empty/$(OPT) a100=1 ptxas=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/F2F_64_32_empty/$(OPT) a100=1 ptxas=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/IMAD_IADD_no_mul/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/IMAD_MOV_U32/$(OPT) a100=1 ptxas=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/LDC128/$(OPT) a100=1
testing:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/F2F_32_F2F/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/F2F_64_F2F/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/F2F_32_64_empty_v2/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/F2F_64_32_empty_v2/$(OPT) a100=1 ptxas=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/LDG_DRAM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG64_STRONG_DRAM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STL8/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDL8/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STL16/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDL16/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STL/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDL/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STL64/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDL64/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STL128/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDL128/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/DADD_DMUL_base/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/DADD_DMUL_DMUL/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C testing_benchmarks/DADD_DMUL_twice/$(OPT) a100=1
new:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDSM_16_MT88_4/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDSM_16_M88_4/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDGSTS_LTC128B_128/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDGSTS_LTC128B_128_CCTL/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDG64_STRONG_L2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STG128_STRONG_L2_v2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/STS_128_v2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C cache_and_data_width_mem_benchmarks/LDGSTS_LTC128B_128_OFFSET/$(OPT) a100=1
	# $(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C inline_asm_benchmarks/BSSY/$(OPT) a100=1 ptxas=1

tensor:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C tensor_benchmarks/TENSOR/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C tensor_benchmarks/TENSOR16/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C tensor_benchmarks/TENSOR32/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C tensor_benchmarks/TENSOR64/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C tensor_benchmarks/TENSOR_TF/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C tensor_benchmarks/TENSOR_TF_1684/$(OPT) a100=1

static_power:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/ACT_CORE1/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/ACT_CORE2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/INT_STATIC/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/INT_FP_STATIC/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/INT_FP_DP_STATIC/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/INT_FP_TENSOR_STATIC/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/INT_FP_TEX_STATIC/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/INT_FP_SFU_STATIC/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/LIGHT_SM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/DP_ADD/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/DP_MAD/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/DP_MUL/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/FP_ADD/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/FP_MAD/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C static_power_modeling/FP_MUL/$(OPT) a100=1

branching:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_l32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_leven/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_ADD_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_l32/$(OPT)  
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_INT_MUL_leven/$(OPT) 
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_l32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_ADD_leven/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_l32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_DIV_leven/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_l32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C branching_benchmarks/BE_SP_FP_MUL_leven/$(OPT)

functional:
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/REG_FILE/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_INT_ADD/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_INT_DIV/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_INT_MUL/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_INT_MUL24/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_INT_MUL32/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_INT_LOGIC/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_FP_ADD/$(OPT) a100=1       
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_FP_DIV/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_FP_MUL/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SP_FP_MAD/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_DP_FP_MAD/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_DP_FP_ADD/$(OPT) a100=1       
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_DP_FP_DIV/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_DP_FP_MUL/$(OPT) a100=1   	
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SFU_EXP/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SFU_LG2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SFU_SIN/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_SFU_SQRT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_HP_FP_ADD/$(OPT) a100=1       
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_HP_FP_MUL/$(OPT) a100=1       
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_HP_FP_MAD/$(OPT) a100=1       
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C functional_benchmarks/BE_HP_FP_DIV/$(OPT) a100=1    

memories:
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_TEXTURE_ACCESS_2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_MEM_SHRD_Acss/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_MEM_CNST_Acss/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_L1D_MISS/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_L1D_HIT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_L2D_HIT/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_L2D_MISS/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_MEM_DRAM_Acss/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/BE_TEXTURE_ACCESS_2/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/FE_IL0_HIT/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/FE_IL1_HIT/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/FE_IL1_MISS/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l1d_stress/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l1r1/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l1r2/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l1r3/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l1r4/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l1r5/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r1/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r2/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r3/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r4/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r5/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r6/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r7/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r8/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2r9/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w1/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w2/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w3/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w4/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w5/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w6/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w7/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w8/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C memories_benchmarks/l2w9/$(OPT) a100=1	

mix:	
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BE_SP_INT/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BE_SP_FP/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BE_SP_INT_FP
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BE_SFU/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/PP_FP_MEM/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BE_TEXTURE_ACCESS/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/add_mem_1/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/add_mem_2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mul_add_tex_1/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mul_add_tex_2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mul_mem_1/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mul_mem_2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BRANCHING1/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BRANCHING2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BRANCHING3/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BRANCHING4/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/BRANCHING5/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/SHRD_TEX_SFU/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/const_mul/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/immediates_constant/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/immediates_texture/$(OPT) a100=1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/shrd_cnst/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix1/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix2/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix3/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix4/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix5/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix6/$(OPT) a100=1  
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix7/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix8/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix9/$(OPT) a100=1  
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix10/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix11/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix12/$(OPT) a100=1 
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix13/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix14/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix15/$(OPT) a100=1 
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix16/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix17/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix18/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix19/$(OPT) a100=1
	$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C mix_benchmarks/mix20/$(OPT) a100=1 	
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C POWER/shrd_tex_1
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C POWER/shrd_tex_2
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C POWER/shrd_tex_fp
	#$(SETENV) make $(MAKE_ARGS) noinline=$(noinline) -C POWER/shrd_tex_sfu

cleaninline:
	$(SETENV) make $(MAKE_ARGS) clean -C inline_asm_benchmarks/MOV/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C inline_asm_benchmarks/NOP/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C inline_asm_benchmarks/BAR/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C inline_asm_benchmarks/LDS/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C inline_asm_benchmarks/STS/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C testing_benchmarks/LDG/$(OPT)

cleantensor:
	$(SETENV) make $(MAKE_ARGS) clean -C tensor_benchmarks/TENSOR/$(OPT)   

cleanstatic:
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/ACT_CORE1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/ACT_CORE2/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/INT_STATIC/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/INT_FP_STATIC/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/INT_FP_DP_STATIC/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/INT_FP_TENSOR_STATIC/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/INT_FP_TEX_STATIC/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/INT_FP_SFU_STATIC/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C static_power_modeling/LIGHT_SM/$(OPT)

cleanfunctional:
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/REG_FILE/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/MOV/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_INT_ADD/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_INT_DIV/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_INT_MUL/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_INT_MUL24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_INT_MUL32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_INT_LOGIC/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_FP_ADD/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_FP_DIV/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_FP_MUL/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SP_FP_MAD/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_DP_FP_MAD/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_DP_FP_ADD/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_DP_FP_DIV/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_DP_FP_MUL/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SFU_EXP/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SFU_LG2/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SFU_SIN/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_SFU_SQRT/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_HP_FP_ADD/$(OPT)       
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_HP_FP_MUL/$(OPT)       
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_HP_FP_MAD/$(OPT)       
	$(SETENV) make $(MAKE_ARGS) clean -C functional_benchmarks/BE_HP_FP_DIV/$(OPT)  

cleanmemories:
	$(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_TEXTURE_ACCESS_2/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_MEM_SHRD_Acss/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_MEM_CNST_Acss/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_L1D_MISS/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_L1D_HIT/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_L2D_HIT/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_MEM_DRAM_Acss/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_MEM_ACCESS/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/BE_TEXTURE_ACCESS_2/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/FE_IL0_HIT/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/FE_IL1_HIT/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/FE_IL1_MISS/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l1d_stress/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r1/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r2/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r3/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r4/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r5/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r6/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r7/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r8/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2r9/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w1/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w2/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w3/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w4/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w5/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w6/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w7/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w8/$(OPT)
	# $(SETENV) make $(MAKE_ARGS) clean -C memories_benchmarks/l2w9/$(OPT)

cleanbranching:
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_l32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_leven/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_ADD_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_l32/$(OPT)  
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_INT_MUL_leven/$(OPT) 
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_l32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_ADD_leven/$(OPT) 
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_l32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_DIV_leven/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l12/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l20/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l24/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l28/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_l32/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_lodd/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C branching_benchmarks/BE_SP_FP_MUL_leven/$(OPT)	

cleanmix:	
	#$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BE_SP_INT/$(OPT)
	#$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BE_SP_FP/$(OPT)
	#$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BE_SP_INT_FP
	#$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BE_SFU/$(OPT)
	#$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/PP_FP_MEM/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BE_TEXTURE_ACCESS/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/add_mem_1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/add_mem_2/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mul_add_tex_1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mul_add_tex_2/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mul_mem_1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mul_mem_2/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BRANCHING1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BRANCHING2/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BRANCHING3/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BRANCHING4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/BRANCHING5/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/SHRD_TEX_SFU/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/const_mul/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/immediates_constant/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/immediates_texture/$(OPT)
	#$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/shrd_cnst/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix1/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix2/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix3/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix4/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix5/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix6/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix7/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix8/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix9/$(OPT)  
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix10/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix11/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix12/$(OPT) 
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix13/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix14/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix15/$(OPT) 
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix16/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix17/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix18/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix19/$(OPT)
	$(SETENV) make $(MAKE_ARGS) clean -C mix_benchmarks/mix20/$(OPT) 	
	#$(SETENV) make $(MAKE_ARGS) clean -C POWER/shrd_tex_1
	#$(SETENV) make $(MAKE_ARGS) clean -C POWER/shrd_tex_2
	#$(SETENV) make $(MAKE_ARGS) clean -C POWER/shrd_tex_fp
	#$(SETENV) make $(MAKE_ARGS) clean -C POWER/shrd_tex_sfu

# power: branching functional memories mix tensor static_power inline
# cleanpower: cleanbranching cleanfunctional cleanmemories cleanmix cleanstatic cleaninline

power: functional memories mix tensor static_power inline
cleanpower: cleanfunctional cleanmemories cleanmix cleanstatic cleaninline
	
